name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          # Navigate to project directory
          cd /var/www/hackweekend
          
          # Create logs directory
          mkdir -p logs
          
          # Backup database
          timestamp=$(date +%Y%m%d_%H%M%S)
          mkdir -p /opt/strapi/database/backup
          cp /opt/strapi/database/data.db "/opt/strapi/database/backup/data.db.$timestamp"
          
          # Update code
          git pull origin main
          
          # Setup Node environment
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 18
          
          # Navigate to backend directory and install dependencies
          cd backend/hackweekend
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          
          # Create PM2 ecosystem file
          cat > ecosystem.config.js << 'EOL'
          module.exports = {
            apps: [{
              name: 'strapi',
              cwd: '/var/www/hackweekend/backend/hackweekend',
              script: 'npm',
              args: 'run develop',
              env: {
                NODE_ENV: 'development',
                DATABASE_CLIENT: 'sqlite',
                DATABASE_FILENAME: '/opt/strapi/database/data.db',
                HOST: '0.0.0.0',
                PORT: 1337,
                PUBLIC_URL: 'https://api.hackwknd.sarawak.digital'
              },
              error_file: "/var/www/hackweekend/logs/strapi-error.log",
              out_file: "/var/www/hackweekend/logs/strapi-out.log",
              time: true
            }]
          }
          EOL
          
          # Update permissions
          sudo chown -R $USER:$USER /opt/strapi/database
          sudo chmod 644 /opt/strapi/database/data.db
          
          # Stop current process and clear PM2 cache
          pm2 delete strapi || true
          pm2 flush
          
          # Start using PM2 ecosystem
          pm2 start ecosystem.config.js
          pm2 save
          
          # Verify deployment
          sleep 10
          if ! pm2 show strapi | grep -q "online"; then
            echo "Deployment failed - Strapi is not running"
            cat /var/www/hackweekend/logs/strapi-error.log
            exit 1
          fi
